import os
import re
import json
import html
import base64
import string
import random
import asyncio
import logging
import secrets
import binascii
import datetime
import urllib.parse
import aiohttp
from aiohttp import web

# ---------------- LOGGING ----------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger("bot")

# ---------------- CONFIG ----------------
BOT_TOKEN = os.environ.get("BOT_TOKEN", "")

WORKER_BASE_URL = os.environ.get("WORKER_BASE_URL", "https://my-worker.dev")
RENDER_APP_BASE_URL = os.environ.get("RENDER_APP_BASE_URL", "https://my-render-app.onrender.com")
PORT = int(os.environ.get("PORT", "8080"))

# Shared secret for the Worker's /api/* endpoints. Must match the Worker's
# API_SECRET. Without it the Worker refuses delete/timer requests.
API_SECRET = os.environ.get("API_SECRET", "")

# shrinkme.io URL shortener API key
SHRINKME_API_KEY = os.environ.get("SHRINKME_API_KEY", "")
SHRINKME_API_URL = "https://shrinkme.io/api"

# Secret used both to build an unguessable webhook path AND as Telegram's
# secret_token header, so random POSTs to /webhook/* can't spoof updates.
WEBHOOK_SECRET = os.environ.get("WEBHOOK_SECRET", secrets.token_urlsafe(24))
WEBHOOK_PATH = f"/webhook/{WEBHOOK_SECRET}"

TG_API = f"https://api.telegram.org/bot{BOT_TOKEN}"

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DL_HTML_PATH = os.path.join(BASE_DIR, "dl.html")
SETTINGS_PATH = os.path.join(BASE_DIR, "settings.json")

URL_REGEX = re.compile(r"^https?://\S+$", re.IGNORECASE)

# Matches any /watch/<id> link regardless of domain, plus an optional query string.
# Group 1 = domain, Group 2 = short id, Group 3 = query string (without "?") or None.
FILETOLINK_URL_REGEX = re.compile(r"https?://([a-zA-Z0-9.-]+)/watch/([A-Za-z0-9_-]+)(?:\?(\S*))?")

# Only characters that can legitimately appear in a hostname (same set the
# FILETOLINK_URL_REGEX domain group allows).
DOMAIN_REGEX = re.compile(r"[a-zA-Z0-9.-]+")

# Link ids generated by the Worker (letters/digits, 8 chars) - validated before use.
LINK_ID_REGEX = re.compile(r"[A-Za-z0-9_-]{1,64}")

DEFAULT_FALLBACK_FILENAME = "Video.mkv"

# ---------------- SETTINGS / CLEANER CONFIG ----------------
SETTINGS_BUTTON_TEXT = "⚙️ Settings"
MAIN_REPLY_KEYBOARD = {
    "keyboard": [[{"text": SETTINGS_BUTTON_TEXT}]],
    "resize_keyboard": True,
    "is_persistent": True,
}

CB_SET_PREFIX = "set_prefix"
CB_SET_BLACKLIST = "set_blacklist"
CB_CLEAR_PREFIX = "clear_prefix"
CB_REMOVE_BLACKLIST_WORD = "remove_blacklist_word"

# Link management buttons (callback_data is limited to 64 bytes)
CB_DELETE_PREFIX = "del:"        # del:<id>
CB_TIMER_PREFIX = "tmr:"         # tmr:<id>
CB_TIMER_UNIT_PREFIX = "tmu:"    # tmu:<h|d>:<id>

STATE_AWAIT_PREFIX = "await_prefix"
STATE_AWAIT_BLACKLIST = "await_blacklist"
STATE_AWAIT_REMOVE_BLACKLIST = "await_remove_blacklist"

MAX_PREFIX_LEN = 100
MAX_BLACKLIST_ENTRIES = 50
MAX_BLACKLIST_ENTRY_LEN = 40

MAX_TTL_DAYS = 365

CLEAR_WORDS = {"none", "clear", "off", "remove", "delete", "-"}

# Any word starting with @ (e.g. @123_321, @kirankiss). Not matched when glued
# to a preceding letter/digit (emails like a@b.com) or to a "/" (URLs like
# medium.com/@user), so those are left alone. Used on FILE NAMES only.
USERNAME_REGEX = re.compile(r"(?<![A-Za-z0-9/])@[A-Za-z0-9_]+")

# Straight and curly apostrophes. They break quoted strings in browsers/players.
APOSTROPHE_REGEX = re.compile(r"['\u2019\u2018]")

# Empty bracket pairs left behind after a removal, e.g. "[@user]" -> "[]".
EMPTY_BRACKETS_REGEX = re.compile(r"\[[\s_.\-]*\]|\([\s_.\-]*\)|\{[\s_.\-]*\}")

# Decides if a blacklist entry is URL/domain-like or a plain word (plain words
# are removed on word boundaries).
URLISH_REGEX = re.compile(r"^(?:https?://|www\.)|/|^[^\s/]+\.[A-Za-z]{2,}$", re.IGNORECASE)

# In-memory state: user_id -> pending URL waiting for a filename
pending_urls = {}

# In-memory state: user_id -> which settings input the bot is waiting for
user_states = {}

# In-memory state: user_id -> {"id": link id, "unit": "h" | "d"} while waiting for the timer number
ttl_states = {}

_session: aiohttp.ClientSession | None = None


async def get_session() -> aiohttp.ClientSession:
    global _session
    if _session is None or _session.closed:
        _session = aiohttp.ClientSession()
    return _session


async def tg_call(method: str, payload: dict) -> dict:
    session = await get_session()
    async with session.post(
        f"{TG_API}/{method}", json=payload, timeout=aiohttp.ClientTimeout(total=20)
    ) as resp:
        data = await resp.json()
        if not data.get("ok"):
            logger.warning(f"[TG API] {method} failed: {data}")
        return data


async def send_message(chat_id: int, text: str, reply_markup: dict | None = None):
    payload = {"chat_id": chat_id, "text": text, "parse_mode": "HTML"}
    if reply_markup:
        payload["reply_markup"] = reply_markup
    return await tg_call("sendMessage", payload)


async def edit_message(chat_id: int, message_id: int, text: str, reply_markup: dict | None = None):
    payload = {"chat_id": chat_id, "message_id": message_id, "text": text, "parse_mode": "HTML"}
    if reply_markup:
        payload["reply_markup"] = reply_markup
    return await tg_call("editMessageText", payload)


async def copy_message(
    chat_id: int,
    from_chat_id: int,
    message_id: int,
    caption: str | None = None,
    reply_markup: dict | None = None,
):
    payload = {
        "chat_id": chat_id,
        "from_chat_id": from_chat_id,
        "message_id": message_id,
        "parse_mode": "HTML",
    }
    # Omitting "caption" tells Telegram to keep the original caption, so we
    # only include it when we actually have a (possibly rewritten) one.
    if caption is not None:
        payload["caption"] = caption
    if reply_markup:
        payload["reply_markup"] = reply_markup
    return await tg_call("copyMessage", payload)


async def answer_callback(callback_id: str | None, text: str | None = None, alert: bool = False):
    """Acknowledges a button press (otherwise Telegram shows a loading spinner)."""
    if not callback_id:
        return
    payload = {"callback_query_id": callback_id}
    if text:
        payload["text"] = text
        if alert:
            payload["show_alert"] = True
    await tg_call("answerCallbackQuery", payload)


async def remove_buttons(chat_id: int, message_id: int | None):
    """Strips the inline keyboard from a message."""
    if message_id is None:
        return
    await tg_call(
        "editMessageReplyMarkup",
        {"chat_id": chat_id, "message_id": message_id, "reply_markup": {"inline_keyboard": []}},
    )


def gen_short_id(length: int = 8) -> str:
    chars = string.ascii_letters + string.digits
    return "".join(random.choice(chars) for _ in range(length))


async def set_webhook():
    webhook_url = f"{RENDER_APP_BASE_URL}{WEBHOOK_PATH}"
    result = await tg_call(
        "setWebhook",
        {
            "url": webhook_url,
            "secret_token": WEBHOOK_SECRET,
            "drop_pending_updates": True,
            "allowed_updates": ["message", "channel_post", "callback_query"],
        },
    )
    logger.info(f"[SET WEBHOOK] url={webhook_url} result={result}")

    info = await tg_call("getWebhookInfo", {})
    logger.info(f"[WEBHOOK INFO] {info}")


# ---------------- URL ENCODING ----------------

def q(value: str) -> str:
    """
    Strict percent-encoding for query values AND path segments.
    Spaces -> %20, & -> %26, + -> %2B, etc. Nothing is left unescaped
    except letters, digits and "_.-~", so names survive every hop
    (Telegram -> Worker -> Render -> player).
    """
    return urllib.parse.quote(str(value), safe="")


def strip_apostrophes(text: str) -> str:
    """"The Butcher's Blade" -> "The Butcher s Blade" (also handles curly apostrophes)."""
    text = APOSTROPHE_REGEX.sub(" ", text or "")
    return re.sub(r"\s{2,}", " ", text).strip()


# ---------------- WORKER API ----------------

async def worker_api(path: str, payload: dict) -> tuple[int, dict]:
    """POSTs JSON to the Worker with the shared secret. Returns (status, json_body)."""
    headers = {"Content-Type": "application/json"}
    if API_SECRET:
        headers["X-API-Secret"] = API_SECRET

    session = await get_session()
    async with session.post(
        f"{WORKER_BASE_URL}{path}",
        json=payload,
        headers=headers,
        timeout=aiohttp.ClientTimeout(total=20),
    ) as resp:
        try:
            data = await resp.json(content_type=None)
        except Exception:
            data = {}
        if not isinstance(data, dict):
            data = {}
        return resp.status, data


async def register_link(url: str, name: str, owner: int | None = None) -> str:
    payload = {"url": url, "name": name}
    if owner is not None:
        payload["owner"] = owner

    status, data = await worker_api("/api/add", payload)
    if status != 200:
        raise RuntimeError(f"Worker returned {status}: {data}")

    short_id = data.get("id")
    if not short_id:
        raise RuntimeError(f"Worker response missing 'id': {data}")
    return short_id


# ---------------- URL SHORTENING ----------------

async def shrink_url(long_url: str) -> str:
    """Call shrinkme.io and return the shortened URL, or the original URL on failure."""
    if not SHRINKME_API_KEY:
        logger.warning("[SHRINKME] No API key configured, skipping shortening")
        return long_url

    params = {"api": SHRINKME_API_KEY, "url": long_url}
    session = await get_session()
    try:
        async with session.get(
            SHRINKME_API_URL, params=params, timeout=aiohttp.ClientTimeout(total=15)
        ) as resp:
            data = await resp.json(content_type=None)
    except Exception as e:
        logger.warning(f"[SHRINKME] Request failed: {e}")
        return long_url

    shortened = data.get("shortenedUrl")
    if not shortened:
        logger.warning(f"[SHRINKME] Unexpected response: {data}")
        return long_url

    return shortened


# ---------------- STEALTH MODE (BASE64 DOMAIN) ----------------

def encode_domain(domain: str) -> str:
    """URL-safe base64 of the domain, with '=' padding stripped (re-added on decode)."""
    return base64.urlsafe_b64encode(domain.encode("utf-8")).decode("ascii").rstrip("=")


def decode_domain(value: str) -> str | None:
    """Reverse of encode_domain. Returns None if the value isn't a valid hostname."""
    try:
        padded = value + "=" * (-len(value) % 4)
        decoded = base64.urlsafe_b64decode(padded.encode("ascii")).decode("utf-8")
    except (binascii.Error, UnicodeError, ValueError):
        return None

    decoded = decoded.strip()
    if decoded and DOMAIN_REGEX.fullmatch(decoded):
        return decoded
    return None


# ---------------- USER SETTINGS (settings.json) ----------------

_settings_cache: dict | None = None


def _load_settings() -> dict:
    global _settings_cache
    if _settings_cache is not None:
        return _settings_cache

    data: dict = {}
    try:
        with open(SETTINGS_PATH, "r", encoding="utf-8") as f:
            loaded = json.load(f)
        if isinstance(loaded, dict):
            data = loaded
    except FileNotFoundError:
        pass
    except (OSError, ValueError) as e:
        logger.warning(f"[SETTINGS] Could not read {SETTINGS_PATH}: {e}")

    _settings_cache = data
    return data


def _save_settings(data: dict) -> bool:
    tmp_path = SETTINGS_PATH + ".tmp"
    try:
        with open(tmp_path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        os.replace(tmp_path, SETTINGS_PATH)
        return True
    except OSError as e:
        logger.error(f"[SETTINGS] Could not write {SETTINGS_PATH}: {e}")
        return False


def get_user_settings(user_id) -> dict:
    """Returns {"prefix": str, "blacklist": list[str]} for a user (safe defaults if unset)."""
    entry = _load_settings().get(str(user_id), {})
    if not isinstance(entry, dict):
        entry = {}

    prefix = entry.get("prefix", "")
    if not isinstance(prefix, str):
        prefix = ""

    raw_blacklist = entry.get("blacklist", [])
    if not isinstance(raw_blacklist, list):
        raw_blacklist = []
    blacklist = [w for w in raw_blacklist if isinstance(w, str) and w.strip()]

    return {"prefix": prefix.strip(), "blacklist": blacklist}


def update_user_settings(user_id, **changes) -> bool:
    """Updates a user's settings in memory and on disk. Returns False if the disk write failed."""
    data = _load_settings()
    entry = data.get(str(user_id))
    if not isinstance(entry, dict):
        entry = {}
    entry.update(changes)
    data[str(user_id)] = entry
    return _save_settings(data)


# ---------------- FILE NAME CLEANER ----------------

def remove_blacklisted(text: str, blacklist: list[str]) -> str:
    """
    Removes blacklisted words/URLs from a file name (case-insensitive).
    Plain words are matched on word boundaries, where "_", ".", "-" and spaces
    all count as boundaries (so "Movie_TamilMV_1080p" works). URL/domain-like
    entries are removed as the exact matched text.
    """
    for entry in sorted(blacklist, key=len, reverse=True):
        if not entry:
            continue
        escaped = re.escape(entry)
        if URLISH_REGEX.search(entry):
            pattern = escaped
        else:
            pattern = rf"(?<![^\W_]){escaped}(?![^\W_])"
        text = re.sub(pattern, "", text, flags=re.IGNORECASE)
    return text


def tidy_name(text: str) -> str:
    """Cleans leftovers (empty brackets, double spaces, doubled underscores) from a filename stem."""
    text = EMPTY_BRACKETS_REGEX.sub("", text)
    text = re.sub(r"[ _]{2,}", lambda m: "_" if "_" in m.group(0) else " ", text)
    text = re.sub(r"\.{2,}", ".", text)
    text = re.sub(r"\s{2,}", " ", text)
    return text.strip(" \t_.-")


def clean_file_name(file_name: str, settings: dict) -> str:
    """
    Pipeline for the file name:
      1) remove @usernames, 2) remove blacklisted words, 3) tidy leftovers,
      4) prepend the auto prefix, 5) replace apostrophes with spaces.
    The extension is never touched.
    """
    name = file_name or ""
    stem, ext = name, ""
    root, suffix = os.path.splitext(name)
    if root and re.fullmatch(r"\.[A-Za-z0-9]{1,5}", suffix):
        stem, ext = root, suffix

    cleaned = USERNAME_REGEX.sub("", stem)
    cleaned = remove_blacklisted(cleaned, settings["blacklist"])
    if cleaned != stem:
        cleaned = tidy_name(cleaned)
    stem = cleaned

    prefix = re.sub(r'[\\/:*?"<>|\x00-\x1f]', "", settings["prefix"]).strip()
    if prefix:
        stem = f"{prefix} {stem}".strip()

    # Apostrophes would break quoted strings in browsers/players.
    stem = strip_apostrophes(stem)

    if not stem:
        stem = "Video"

    result = stem + ext
    # Path separators / control characters never belong in a file name.
    result = re.sub(r"[\\/\x00-\x1f]", "", result)
    return result or DEFAULT_FALLBACK_FILENAME


# ---------------- SETTINGS MENU UI ----------------

def is_settings_request(text: str) -> bool:
    normalized = text.replace("\ufe0f", "").strip().lower()
    return (
        normalized in {"⚙ settings", "settings", "/settings"}
        or normalized.startswith("/settings@")
    )


def parse_blacklist_input(raw: str) -> list[str]:
    """Comma/newline separated entries (phrases allowed); plain whitespace-separated if neither is used."""
    raw = raw.strip()
    if raw.lower() in CLEAR_WORDS:
        return []

    if re.search(r"[,\n]", raw):
        parts = re.split(r"[,\n]+", raw)
    else:
        parts = raw.split()

    seen = set()
    entries = []
    for part in parts:
        part = part.strip()[:MAX_BLACKLIST_ENTRY_LEN]
        if not part:
            continue
        key = part.lower()
        if key in seen:
            continue
        seen.add(key)
        entries.append(part)
        if len(entries) >= MAX_BLACKLIST_ENTRIES:
            break
    return entries


async def send_settings_menu(chat_id: int, user_id: int):
    settings = get_user_settings(user_id)

    prefix_display = html.escape(settings["prefix"]) if settings["prefix"] else "<i>not set</i>"

    if settings["blacklist"]:
        joined = ", ".join(settings["blacklist"])
        if len(joined) > 700:
            joined = joined[:700] + "…"
        blacklist_display = html.escape(joined)
    else:
        blacklist_display = "<i>not set</i>"

    text = (
        "⚙️ <b>Settings</b>\n\n"
        f"<b>Auto Prefix:</b> {prefix_display}\n"
        f"<b>Blacklist:</b> {blacklist_display}"
    )
    reply_markup = {
        "inline_keyboard": [
            [{"text": "Set Auto Prefix", "callback_data": CB_SET_PREFIX}],
            [{"text": "Set Blacklist Words", "callback_data": CB_SET_BLACKLIST}],
            [{"text": "🗑 Clear Auto Prefix", "callback_data": CB_CLEAR_PREFIX}],
            [{"text": "➖ Remove Blacklist Word", "callback_data": CB_REMOVE_BLACKLIST_WORD}],
        ]
    }
    await send_message(chat_id, text, reply_markup)


# ---------------- LINK MANAGEMENT (DELETE / TIMER) ----------------

def link_buttons(watch_url: str, short_id: str) -> dict:
    """Watch button on top, Delete + Timer side by side below it."""
    return {
        "inline_keyboard": [
            [{"text": "▶️ Watch / Download", "url": watch_url}],
            [
                {"text": "🗑 Delete", "callback_data": f"{CB_DELETE_PREFIX}{short_id}"},
                {"text": "⏳ Timer", "callback_data": f"{CB_TIMER_PREFIX}{short_id}"},
            ],
        ]
    }


async def handle_delete_callback(
    callback_id: str | None, user_id: int, chat_id: int, message_id: int | None, link_id: str
):
    if not LINK_ID_REGEX.fullmatch(link_id):
        await answer_callback(callback_id, "Invalid link.", alert=True)
        return

    try:
        status, data = await worker_api("/api/delete", {"id": link_id, "owner": user_id})
    except Exception as e:
        logger.warning(f"[DELETE] Worker request failed: {e}")
        await answer_callback(callback_id, "⚠️ Couldn't reach the server. Try again.", alert=True)
        return

    if status == 200:
        await answer_callback(callback_id, "🗑 Link deleted.")
        await remove_buttons(chat_id, message_id)
    elif status == 404:
        await answer_callback(callback_id, "This link was already deleted.")
        await remove_buttons(chat_id, message_id)
    elif status == 403:
        await answer_callback(callback_id, "⛔ Only the person who created this link can delete it.", alert=True)
    else:
        logger.warning(f"[DELETE] Worker returned {status}: {data}")
        await answer_callback(callback_id, f"⚠️ Delete failed ({status}).", alert=True)


async def handle_ttl_input(chat_id: int, user_id: int, state: dict, text: str):
    unit = state.get("unit")
    link_id = state.get("id", "")
    raw = text.strip()

    if not re.fullmatch(r"\d{1,5}", raw):
        await send_message(chat_id, "Please send a whole number, for example <code>24</code>. (/cancel to abort)")
        return

    amount = int(raw)
    max_amount = MAX_TTL_DAYS * 24 if unit == "h" else MAX_TTL_DAYS
    unit_name = "hours" if unit == "h" else "days"

    if amount < 1 or amount > max_amount:
        await send_message(chat_id, f"Please send a number between 1 and {max_amount} ({unit_name}).")
        return

    seconds = amount * (3600 if unit == "h" else 86400)

    try:
        status, data = await worker_api(
            "/api/ttl", {"id": link_id, "owner": user_id, "ttl_seconds": seconds}
        )
    except Exception as e:
        logger.warning(f"[TTL] Worker request failed: {e}")
        await send_message(chat_id, "⚠️ Couldn't reach the server. Send the number again to retry, or /cancel.")
        return

    ttl_states.pop(user_id, None)

    if status == 200:
        expires_at = data.get("expires_at")
        when = ""
        if isinstance(expires_at, (int, float)):
            dt = datetime.datetime.fromtimestamp(expires_at / 1000, tz=datetime.timezone.utc)
            when = f"\nExpires: <code>{dt.strftime('%Y-%m-%d %H:%M')} UTC</code>"
        label = unit_name[:-1] if amount == 1 else unit_name
        await send_message(
            chat_id,
            f"✅ Timer set. This link will be deleted automatically in <b>{amount} {label}</b>.{when}",
        )
    elif status == 404:
        await send_message(chat_id, "❌ This link no longer exists.")
    elif status == 403:
        await send_message(chat_id, "⛔ Only the person who created this link can set a timer on it.")
    else:
        logger.warning(f"[TTL] Worker returned {status}: {data}")
        await send_message(chat_id, f"⚠️ Couldn't set the timer ({status}).")


async def handle_callback_query(callback_query: dict):
    callback_id = callback_query.get("id")
    user_id = (callback_query.get("from") or {}).get("id")
    data = callback_query.get("data") or ""
    message = callback_query.get("message") or {}
    chat_id = (message.get("chat") or {}).get("id")
    message_id = message.get("message_id")

    if user_id is None or chat_id is None:
        await answer_callback(callback_id)
        return

    # ----- Delete -----
    if data.startswith(CB_DELETE_PREFIX):
        await handle_delete_callback(
            callback_id, user_id, chat_id, message_id, data[len(CB_DELETE_PREFIX):]
        )
        return

    # ----- Timer: step 1 (ask Hours or Days) -----
    if data.startswith(CB_TIMER_PREFIX):
        link_id = data[len(CB_TIMER_PREFIX):]
        if not LINK_ID_REGEX.fullmatch(link_id):
            await answer_callback(callback_id, "Invalid link.", alert=True)
            return
        await answer_callback(callback_id)
        await send_message(
            chat_id,
            "⏳ <b>Auto-delete timer</b>\n\nHours or Days?",
            {
                "inline_keyboard": [
                    [
                        {"text": "🕐 Hours", "callback_data": f"{CB_TIMER_UNIT_PREFIX}h:{link_id}"},
                        {"text": "📅 Days", "callback_data": f"{CB_TIMER_UNIT_PREFIX}d:{link_id}"},
                    ]
                ]
            },
        )
        return

    # ----- Timer: step 2 (unit chosen, now wait for the number) -----
    if data.startswith(CB_TIMER_UNIT_PREFIX):
        parts = data[len(CB_TIMER_UNIT_PREFIX):].split(":", 1)
        if len(parts) != 2 or parts[0] not in ("h", "d") or not LINK_ID_REGEX.fullmatch(parts[1]):
            await answer_callback(callback_id, "Invalid request.", alert=True)
            return

        unit, link_id = parts
        await answer_callback(callback_id)

        pending_urls.pop(user_id, None)
        user_states.pop(user_id, None)
        ttl_states[user_id] = {"id": link_id, "unit": unit}

        unit_name = "hours" if unit == "h" else "days"
        example = "24" if unit == "h" else "7"
        await send_message(
            chat_id,
            f"Send the number of <b>{unit_name}</b> after which this link should be deleted "
            f"(for example <code>{example}</code>).\n\n/cancel to abort.",
        )
        return

    # ----- Settings buttons (always acknowledged, otherwise a spinner stays) -----
    await answer_callback(callback_id)

    if data == CB_SET_PREFIX:
        pending_urls.pop(user_id, None)
        ttl_states.pop(user_id, None)
        user_states[user_id] = STATE_AWAIT_PREFIX
        await send_message(
            chat_id,
            "Send me the text to use as <b>Auto Prefix</b> (added to the start of file names).\n\n"
            "Send <code>none</code> to remove it, or /cancel to keep the current one.",
        )
    elif data == CB_SET_BLACKLIST:
        pending_urls.pop(user_id, None)
        ttl_states.pop(user_id, None)
        user_states[user_id] = STATE_AWAIT_BLACKLIST
        await send_message(
            chat_id,
            "Send me the <b>Blacklist words/URLs</b> to remove from file names, "
            "separated by commas or new lines.\n\n"
            "This replaces your current list. Send <code>none</code> to clear it, or /cancel to keep it.",
        )
    elif data == CB_CLEAR_PREFIX:
        saved = update_user_settings(user_id, prefix="")
        reply = "✅ Auto Prefix cleared."
        if not saved:
            reply += "\n\n⚠️ Couldn't write to disk, so this may be lost when the bot restarts."
        await send_message(chat_id, reply)
    elif data == CB_REMOVE_BLACKLIST_WORD:
        pending_urls.pop(user_id, None)
        ttl_states.pop(user_id, None)
        user_states[user_id] = STATE_AWAIT_REMOVE_BLACKLIST
        await send_message(
            chat_id,
            "Send the exact word/URL you want to remove from your blacklist.",
        )


async def handle_settings_input(chat_id: int, user_id: int, state: str, text: str):
    if state == STATE_AWAIT_PREFIX:
        value = " ".join(text.split())
        if value.lower() in CLEAR_WORDS:
            saved = update_user_settings(user_id, prefix="")
            reply = "✅ Auto Prefix removed."
        else:
            trimmed = len(value) > MAX_PREFIX_LEN
            value = value[:MAX_PREFIX_LEN].strip()
            saved = update_user_settings(user_id, prefix=value)
            reply = f"✅ Auto Prefix saved: <b>{html.escape(value)}</b>"
            if trimmed:
                reply += f"\n(Trimmed to {MAX_PREFIX_LEN} characters.)"
    elif state == STATE_AWAIT_BLACKLIST:
        entries = parse_blacklist_input(text)
        saved = update_user_settings(user_id, blacklist=entries)
        if entries:
            shown = ", ".join(entries)
            if len(shown) > 700:
                shown = shown[:700] + "…"
            reply = f"✅ Blacklist saved ({len(entries)}): {html.escape(shown)}"
        else:
            reply = "✅ Blacklist cleared."
    elif state == STATE_AWAIT_REMOVE_BLACKLIST:
        target = text.strip()
        target_display = html.escape(target[:100])
        current = get_user_settings(user_id)["blacklist"]
        remaining = [w for w in current if w.lower() != target.lower()]

        if len(remaining) == len(current):
            await send_message(chat_id, f"❌ <b>{target_display}</b> was not found in your blacklist.")
            return

        saved = update_user_settings(user_id, blacklist=remaining)
        reply = f"✅ Removed <b>{target_display}</b> from your blacklist."
    else:
        return

    if not saved:
        reply += "\n\n⚠️ Couldn't write to disk, so this may be lost when the bot restarts."

    await send_message(chat_id, reply)


# ---------------- FILE-TO-LINK MESSAGE HANDLING ----------------

def extract_media_file_name(message: dict) -> str | None:
    """Pull the original file name straight from the media's own metadata."""
    document = message.get("document")
    if document and document.get("file_name"):
        return document["file_name"]

    video = message.get("video")
    if video and video.get("file_name"):
        return video["file_name"]

    return None


def has_media(message: dict) -> bool:
    return bool(
        message.get("document") or message.get("video") or message.get("photo")
    )


async def handle_filetolink_message(message: dict):
    """
    Processes a message/caption that contains one or more /watch/<id> links:
      - cleans ONLY the file name (@usernames, blacklist, auto prefix,
        apostrophes) used to build the watch URL,
      - builds a fresh watch URL using that file name (or a fallback for plain
        text), hiding the external domain as base64,
      - preserves any original query string (e.g. ?hash=...) of the link,
      - shortens it via shrinkme.io,
      - swaps ONLY the matched link for the shortened URL; the rest of the
        caption/message text is kept exactly as received (no cleaning),
      - reposts the payload (copying media, or sending plain text) with an
        inline "Watch online & Download" button.

    NOTE: these links live on the external server, not in the Worker's KV
    database, so there is nothing for Delete / Timer buttons to act on here.
    """
    chat = message.get("chat", {})
    chat_id = chat.get("id")
    message_id = message.get("message_id")
    if chat_id is None or message_id is None:
        return

    is_media = has_media(message)
    original_text = message.get("caption") if is_media else message.get("text")
    original_text = original_text or ""

    match = FILETOLINK_URL_REGEX.search(original_text)
    if not match:
        return

    extracted_domain = match.group(1)
    short_id = match.group(2)

    user_id = (message.get("from") or {}).get("id")
    settings = get_user_settings(user_id)

    # --- File name cleaning (usernames -> blacklist -> tidy -> prefix -> apostrophes) ---
    raw_file_name = extract_media_file_name(message) or DEFAULT_FALLBACK_FILENAME
    file_name = clean_file_name(raw_file_name, settings)

    # Strict encoding: spaces -> %20, etc.
    encoded_name = q(file_name)

    # Stealth mode: the external domain is never sent in plain text.
    b64_domain = encode_domain(extracted_domain)

    # External domain Workers don't run the /watch/ HTML proxy themselves, so
    # the link points at the central proxy worker (WORKER_BASE_URL), passing
    # the (base64-hidden) external domain through explicitly so Render can
    # build a /dl/ link back to it.
    orig_query = match.group(3) or ""

    base_url = f"{WORKER_BASE_URL}/watch/{short_id}?name={encoded_name}&b64_domain={b64_domain}"
    if orig_query:
        base_url += f"&orig_query={q(orig_query)}"

    shortened_url = await shrink_url(base_url)

    # The caption/message text is NOT cleaned or modified in any way. Only the
    # matched link is replaced by the shortened URL. The text before and after
    # the link is HTML-escaped (required by parse_mode HTML so stray < or &
    # don't break the message) but otherwise kept exactly as received.
    before_link = html.escape(original_text[: match.start()])
    after_link = html.escape(original_text[match.end():])
    new_text = f"{before_link}{html.escape(shortened_url, quote=False)}{after_link}"

    reply_markup = {
        "inline_keyboard": [[{"text": "Watch online & Download", "url": base_url}]]
    }

    if is_media:
        await copy_message(
            chat_id=chat_id,
            from_chat_id=chat_id,
            message_id=message_id,
            caption=new_text,
            reply_markup=reply_markup,
        )
    else:
        await send_message(chat_id, new_text, reply_markup)


# ---------------- UPDATE HANDLING ----------------

async def handle_message(message: dict):
    chat = message.get("chat", {})
    chat_id = chat.get("id")
    from_user = message.get("from", {})
    user_id = from_user.get("id")
    text = (message.get("text") or "").strip()
    caption = (message.get("caption") or "").strip()

    if chat_id is None or user_id is None:
        return

    logger.info(f"[MESSAGE] user_id={user_id} text={text!r}")

    # Route messages/captions that already contain a /watch/<id> link to the
    # dedicated file-to-link handler, regardless of domain.
    if FILETOLINK_URL_REGEX.search(text) or FILETOLINK_URL_REGEX.search(caption):
        # The user moved on from any pending settings/timer prompt.
        user_states.pop(user_id, None)
        ttl_states.pop(user_id, None)
        await handle_filetolink_message(message)
        return

    command = ""
    if text.startswith("/"):
        command = text.split(maxsplit=1)[0].split("@")[0].lower()

    # Settings menu (reply keyboard button or /settings)
    if is_settings_request(text):
        pending_urls.pop(user_id, None)
        user_states.pop(user_id, None)
        ttl_states.pop(user_id, None)
        await send_settings_menu(chat_id, user_id)
        return

    if text.startswith("/start"):
        pending_urls.pop(user_id, None)
        user_states.pop(user_id, None)
        ttl_states.pop(user_id, None)
        await send_message(
            chat_id,
            "Send me a direct URL to begin.\n\nUse <b>⚙️ Settings</b> to set an auto prefix and blacklist words.",
            MAIN_REPLY_KEYBOARD,
        )
        return

    if command == "/cancel":
        had_state = user_states.pop(user_id, None) is not None
        had_pending = pending_urls.pop(user_id, None) is not None
        had_ttl = ttl_states.pop(user_id, None) is not None
        await send_message(
            chat_id,
            "Cancelled." if (had_state or had_pending or had_ttl) else "Nothing to cancel.",
        )
        return

    # Waiting for a settings value (prefix / blacklist)
    state = user_states.get(user_id)
    if state and text:
        user_states.pop(user_id, None)
        await handle_settings_input(chat_id, user_id, state, text)
        return

    # Waiting for the timer number (hours / days). A pasted URL means the user
    # moved on, so it abandons the timer prompt and is handled below.
    ttl_state = ttl_states.get(user_id)
    if ttl_state and text:
        if URL_REGEX.match(text):
            ttl_states.pop(user_id, None)
        else:
            await handle_ttl_input(chat_id, user_id, ttl_state, text)
            return

    # Case 1: user is replying with a filename for a previously sent URL
    if user_id in pending_urls:
        url = pending_urls.pop(user_id)
        filename = text.strip()

        if not filename:
            pending_urls[user_id] = url
            await send_message(chat_id, "Filename can't be empty. Please enter a valid filename (with extension).")
            return

        # Apply the user's cleaners (@usernames, blacklist), Auto Prefix and the
        # apostrophe safeguard to the manually typed filename before it is
        # registered / URL-encoded.
        settings = get_user_settings(user_id)
        filename = clean_file_name(filename, settings)

        status = await send_message(chat_id, "Registering your link, please wait...")
        status_message_id = status.get("result", {}).get("message_id")

        try:
            short_id = await register_link(url, filename, owner=user_id)
        except Exception as e:
            if status_message_id:
                await edit_message(chat_id, status_message_id, f"Failed to register link: {html.escape(str(e))}")
            else:
                await send_message(chat_id, f"Failed to register link: {html.escape(str(e))}")
            return

        encoded_name = q(filename)
        # The Worker proxies /watch/ (fetching dl.html from Render
        # server-side), so the link handed to the user is the Worker's own
        # domain — Render is never exposed to the browser.
        watch_url = f"{WORKER_BASE_URL}/watch/{short_id}?name={encoded_name}"

        # The shortened link is used ONLY in the message text. The inline
        # button below keeps the direct Worker watch_url.
        shortened_url = await shrink_url(watch_url)

        reply_markup = link_buttons(watch_url, short_id)

        final_text = (
            f"Your link is ready!\n\n"
            f"<b>Filename:</b> {html.escape(filename)}\n"
            f"<b>Link:</b> {html.escape(shortened_url, quote=False)}"
        )
        if status_message_id:
            await edit_message(chat_id, status_message_id, final_text, reply_markup)
        else:
            await send_message(chat_id, final_text, reply_markup)
        return

    # Case 2: user is sending a fresh URL
    if URL_REGEX.match(text):
        pending_urls[user_id] = text
        await send_message(chat_id, "Please enter the custom filename (with extension).")
        return

    # Case 3: not a URL, and no pending state
    await send_message(chat_id, "Please send a valid direct URL to begin.")


# ---------------- WEB SERVER ----------------

async def webhook_handler(request: web.Request) -> web.Response:
    # Verify the secret token Telegram sends back, so only real Telegram
    # requests (matching what we set in setWebhook) are processed.
    incoming_secret = request.headers.get("X-Telegram-Bot-Api-Secret-Token")
    if incoming_secret != WEBHOOK_SECRET:
        logger.warning("[WEBHOOK] Rejected request with bad/missing secret token")
        return web.Response(status=403, text="Forbidden")

    try:
        update = await request.json()
    except Exception:
        return web.Response(status=400, text="Bad Request")

    logger.info(f"[UPDATE RECEIVED] {update.get('update_id')}")

    callback_query = update.get("callback_query")
    if callback_query:
        try:
            await handle_callback_query(callback_query)
        except Exception as e:
            logger.exception(f"[HANDLE_CALLBACK ERROR] {e}")

    message = update.get("message") or update.get("channel_post")
    if message:
        try:
            await handle_message(message)
        except Exception as e:
            logger.exception(f"[HANDLE_MESSAGE ERROR] {e}")

    # Always 200 quickly, or Telegram will retry/backoff this update.
    return web.Response(status=200, text="OK")


async def watch_handler(request: web.Request) -> web.Response:
    short_id = request.match_info.get("id", "")

    if not short_id:
        return web.Response(status=400, text="Missing ID")

    # aiohttp has ALREADY percent-decoded request.query, so do NOT unquote
    # again (a second decode corrupts names containing "%" or "+").
    # Apostrophes are stripped here too so older links keep working safely.
    filename = strip_apostrophes(request.query.get("name", "Video.mp4")) or "Video.mp4"
    name_path = q(filename)  # safe path segment for the player-visible title

    try:
        with open(DL_HTML_PATH, "r", encoding="utf-8") as f:
            template = f.read()
    except FileNotFoundError:
        return web.Response(status=500, text="dl.html template not found on server")

    # Stealth mode: the external domain arrives base64-encoded (b64_domain).
    # The old plain "domain" param is still accepted so links already posted
    # keep working. Either way the value must be a valid hostname.
    target_domain = None
    b64_domain = request.query.get("b64_domain")
    if b64_domain:
        target_domain = decode_domain(b64_domain)
        if not target_domain:
            return web.Response(status=400, text="Invalid domain parameter")
    else:
        legacy_domain = request.query.get("domain")
        if legacy_domain:
            if not DOMAIN_REGEX.fullmatch(legacy_domain):
                return web.Response(status=400, text="Invalid domain parameter")
            target_domain = legacy_domain

    if target_domain:
        # Forwarded links go THROUGH our Worker (/ext/), so the Worker can
        # force the custom filename via Content-Disposition. The name is also
        # placed as the LAST PATH SEGMENT so VLC shows it instead of the ID.
        orig_query = (request.query.get("orig_query") or "").lstrip("?").strip()

        ext_base = f"{WORKER_BASE_URL}/ext/{encode_domain(target_domain)}/{short_id}/{name_path}"
        params = []
        if orig_query:
            params.append(f"oq={q(orig_query)}")

        stream_url = ext_base + ("?" + "&".join(params) if params else "")
        download_url = ext_base + "?" + "&".join(params + ["dl=1"])
    else:
        # Manual registered links: name in the path for VLC, ?dl=1 forces a
        # download disposition instead of inline playback.
        stream_url = f"{WORKER_BASE_URL}/stream/{short_id}/{name_path}"
        download_url = f"{stream_url}?dl=1"

    try:
        # Values are HTML-escaped so a crafted ?name= can't inject markup.
        rendered = template % (
            html.escape(filename),
            html.escape(filename),
            html.escape(stream_url),
            html.escape(download_url),
            "Download",
        )
    except TypeError as e:
        return web.Response(status=500, text=f"Template formatting error: {e}")

    return web.Response(text=rendered, content_type="text/html")


async def health_handler(request: web.Request) -> web.Response:
    return web.Response(text="OK")


def build_web_app() -> web.Application:
    app = web.Application()
    app.router.add_post(WEBHOOK_PATH, webhook_handler)
    app.router.add_get("/watch/{id}", watch_handler)
    app.router.add_get("/health", health_handler)
    return app


async def run_web_server():
    app = build_web_app()
    runner = web.AppRunner(app)
    await runner.setup()
    site = web.TCPSite(runner, "0.0.0.0", PORT)
    await site.start()
    logger.info(f"Web server running on port {PORT}")


async def keepalive_loop():
    await asyncio.sleep(15)
    url = f"{RENDER_APP_BASE_URL}/health"
    session = await get_session()
    while True:
        try:
            async with session.get(url, timeout=aiohttp.ClientTimeout(total=15)) as resp:
                logger.info(f"[KEEPALIVE] pinged {url} -> {resp.status}")
        except Exception as e:
            logger.warning(f"[KEEPALIVE] ping failed: {e}")
        await asyncio.sleep(600)


async def main():
    if not API_SECRET:
        logger.warning("[CONFIG] API_SECRET is not set: Delete/Timer buttons will be rejected by the Worker")
    await run_web_server()
    await set_webhook()
    logger.info("Webhook set. Waiting for updates...")
    asyncio.create_task(keepalive_loop())
    while True:
        await asyncio.sleep(3600)


if __name__ == "__main__":
    asyncio.run(main())
